run-name: "verify_deploy: ${{ github.ref_name }} # ${{ github.sha }}"
on:
   workflow_dispatch:
   workflow_call:
   schedule:
      - cron: "0 19 * * *"

jobs:
   verify-deploy:
      runs-on: deployee
      defaults:
         run:
            working-directory: /var/www/my_web_cv/
      steps:
      - name: verify-required
        run: |
            test -f index.js
            test -f index.html
            test -d assets
            test -d wasm

      - name: verify-optional
        continue-on-error: true
        run: |
         test -L assets/__softlink_cv_eng.pdf
         test -L assets/__softlink_cv_rus.pdf
         readlink -e assets/__softlink_cv_eng.pdf
         readlink -e assets/__softlink_cv_rus.pdf
   verify-server:
      runs-on: deployer
      steps:
      - name: check_web_cv
        run: |
         curl -sSf ${{ secrets.WEB_SERVER }}
         curl -sSf ${{ secrets.WEB_SERVER }}/index.js
         curl -sSf ${{ secrets.WEB_SERVER }}/assets/__softlink_cv_eng.pdf
         curl -sSf ${{ secrets.WEB_SERVER }}/assets/__softlink_cv_rus.pdf
      - name: check_trees_ruler
        run: |
         curl -sSf ${{ secrets.WEB_SERVER }}/trees_ruler
         curl -sSf ${{ secrets.WEB_SERVER }}/trees_ruler/eng
         curl -sSf ${{ secrets.WEB_SERVER }}/trees_ruler/rus
